// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding reference estimates...');

  // Clear existing seeded records
  await prisma.referenceEstimate.deleteMany({});

  const estimates = [
    {
      jobType: 'Stamped Concrete Installation',
      clientName: 'Amy Geiger',
      total: 64781.46,
      originalFilename: 'estimate_4208_amy_geiger.pdf',
      pricingNotes:
        'Stamped concrete ~$47.88/sq ft for 1353 sq ft including demo of existing deck, tree removal, excavation, gravel base, rebar, 4000 PSI air-entrained with integral color, large Ashlar stamp, liquid release, sealer, decorative form liner on steps. 6 reinforced steps included. Excludes permits, utility relocation, unforeseen rock.',
      extractedJson: {
        client_name: 'Amy Geiger',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4208',
        date: '07/30/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Stamped Concrete Installation',
            rate: 64781.46,
            quantity: 1,
            total: 64781.46,
            details:
              'Upper patio 41\'x15\', lower patio 41\'x18\', 3-ft landing, 6 reinforced steps. 1353 sq ft total. Demolition of existing deck, tree removal, excavation, gravel base, rebar, 4000 PSI air-entrained concrete, integral color, large Ashlar stamp finish, liquid release, sealer, decorative form liner on step faces, cleanup.',
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: [
              'Excludes permits, utility relocation, unforeseen rock',
              'Approximately $47.88/sq ft',
            ],
            price_source: 'exact_match',
          },
        ],
        subtotal: 64781.46,
        discount: 0,
        total: 64781.46,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          'Stamped concrete installation 1353 sq ft with demolition, excavation, Ashlar stamp, integral color, sealer, and 6 reinforced steps.',
      },
    },
    {
      jobType: 'Shower Remodel',
      clientName: 'Mathew Counts',
      total: 8900.0,
      originalFilename: 'estimate_4220_mathew_counts.pdf',
      pricingNotes:
        'Shower tear-out labor $1,200 (existing shower, rotted subfloor, door removal). Shower install labor $7,300 (subfloor, Wedi waterproofing, subway tile walls, tile floor, grout, stone curb/niche, fixtures). Customer pays material ($2,000-2,500 behind-scenes). Dump fee $250. Gas surcharge $150. Shower door reinstall add-on: $550.',
      extractedJson: {
        client_name: 'Mathew Counts',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4220',
        date: '08/14/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Tear Out',
            rate: 1200.0,
            quantity: 1,
            total: 1200.0,
            details:
              'Labor Only: tear out existing shower, tear out rotted subfloor, remove shower door for possible reinstall.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Shower Install',
            rate: 7300.0,
            quantity: 1,
            total: 7300.0,
            details:
              'Labor Only, customer pays material (~$2,000-$2,500): install new subfloor where needed, Wedi system on walls/floor/niche to waterproof, subway tile on walls and niche, tile on shower floor, grout, stone on curb and niche ledge, shower fixtures.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: true,
            notes: [
              'Behind-scenes material ~$2,000-$2,500 customer pays',
              'Shower door reinstall (if existing works) = $550 additional',
            ],
            price_source: 'exact_match',
          },
          {
            description: 'Dump Fee',
            rate: 250.0,
            quantity: 1,
            total: 250.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Gas Surcharge',
            rate: 150.0,
            quantity: 1,
            total: 150.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 8900.0,
        discount: 0,
        total: 8900.0,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          'Bathroom shower remodel: tear out existing shower and rotted subfloor, install new Wedi waterproofing system, subway tile walls, tile floor, stone curb/niche, fixtures. Labor only.',
      },
    },
    {
      jobType: 'Concrete Driveway Addition',
      clientName: 'Chad Wolfe',
      total: 4440.78,
      originalFilename: 'estimate_4221_chad_wolfe.pdf',
      pricingNotes:
        'Concrete driveway addition (broom finish) labor+material $4,140.78 includes demo dirt, grade, forms, gravel, fiberglass rebar, fiber mesh mix, 4-inch concrete (thicker apron), broom finish, standard color. Permit processing fee $300 (drawings, application, inspectors). Customer responsible for HOA approval.',
      extractedJson: {
        client_name: 'Chad Wolfe',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4221',
        date: '08/14/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Concrete (Driveway Addition)',
            rate: 4140.78,
            quantity: 1,
            total: 4140.78,
            details:
              'Includes all Labor, Includes all Material: demo dirt, grade area, set forms, install gravel, install fiberglass rebar, fiber mesh mix, 4" concrete (thicker at apron), broom finish, standard color.',
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: ['Customer responsible for HOA approval'],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Cost',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details: 'TBD — added once known',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Processing Fee',
            rate: 300.0,
            quantity: 1,
            total: 300.0,
            details:
              'Labor Only: drawing sketch, applying for permit, time with inspectors.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 4440.78,
        discount: 0,
        total: 4440.78,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          'Concrete driveway addition with broom finish. Includes all labor and material: demo, grading, forms, gravel, fiberglass rebar, fiber mesh, 4-inch concrete, broom finish.',
      },
    },
    {
      jobType: 'Garage Renovation',
      clientName: 'Cody Messmore',
      total: 21549.74,
      originalFilename: 'estimate_4235_cody_messmore.pdf',
      pricingNotes:
        "Garage & exterior restoration (20'x19' garage, 19'x18' concrete area): concrete floor demo/replacement, damaged siding replacement, soffit/fascia repairs, exterior painting 2 coats, gutters & downspouts. All labor+material $21,549.74. Excludes roof repairs, backside garage (not accessible), landscaping, electrical/plumbing, permits.",
      extractedJson: {
        client_name: 'Cody Messmore',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4235',
        date: '08/19/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Garage Renovation',
            rate: 21549.74,
            quantity: 1,
            total: 21549.74,
            details:
              "Includes all — garage 20'x19', concrete area 19'x18': concrete demo and replacement, siding repairs, soffit/fascia repairs, paint entire garage and shed (2 coats, no garage doors), gutters and downspouts.",
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: [
              'Excludes roof repairs, backside garage (not accessible), landscaping, electrical/plumbing, permits',
            ],
            price_source: 'exact_match',
          },
        ],
        subtotal: 21549.74,
        discount: 0,
        total: 21549.74,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          "Garage renovation: concrete floor demo/replacement, siding repairs, soffit/fascia repairs, exterior paint (2 coats), gutters and downspouts for 20'x19' garage.",
      },
    },
    {
      jobType: 'Composite Deck Build',
      clientName: 'Joey Wykoff',
      total: 46671.23,
      originalFilename: 'estimate_4244_joey_wykoff_composite_deck.pdf',
      pricingNotes:
        "Composite deck 17'x27' (full build on pressure treated frame, 20-dia x 30-depth footers, posts, ledger, joists, bump out, 90-degree stair platform landing, deck boards, picture frame, railing, fascia) labor+material $46,671.23. Kids bathroom tub-to-shower conversion + full remodel estimated $19,500 labor only (customer pays finish material): Wedi pan+waterproofing, shower tile+4 shelves, floor tile, plumbing relocation allowance, vanity, toilet, accessories, trim, paint.",
      extractedJson: {
        client_name: 'Joey Wykoff',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4244',
        date: '08/26/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Master Bathroom Remodel',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details: 'TBD, labor only, behind-scenes material ~$3,000-4,000',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: true,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Deck',
            rate: 46671.23,
            quantity: 1,
            total: 46671.23,
            details:
              "Includes all Labor and Material and Cleanup: 17'x27' composite deck built on pressure treated frame, dig footers 20\" dia x 30\" depth, pour cement, install posts, ledger board, floor joists, bump out near stairs, stairs with 90-degree platform landing, deck boards, picture frame border, railing system, fascia on exposed framing.",
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Kids Bathroom Remodel',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details:
              'TBD, tub-to-shower conversion full remodel, labor only, behind-scenes material ~$3,000-4,000. Scope: demo+protection $1,500, tub removal/prep $1,500, water wall+plumbing $1,800, Wedi shower pan+waterproofing $2,500, shower tile+4 corner shelves $2,400, floor demo+tile $1,800, hallway transition $300, drywall repairs $900, vanity+accessories install $1,500, toilet reinstall $350, baseboard+trim $600, painting $1,200. Fixed price $19,500.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: true,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Siding',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details: 'TBD',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Shower Doors',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details: 'TBD',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 46671.23,
        discount: 0,
        total: 46671.23,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          "Composite deck 17'x27' with pressure treated frame, footers, stairs with 90-degree platform landing, picture frame border, railing system. Two bathroom remodels TBD.",
      },
    },
    {
      jobType: 'Pressure Treated Deck Build with Demo',
      clientName: 'Joey Wykoff',
      total: 29490.0,
      originalFilename: 'estimate_4247_joey_wykoff_pt_deck.pdf',
      pricingNotes:
        "Pressure treated deck 17'x27' (18-dia x 33-depth footers, posts, ledger, joists, 36-wide bump out, 1 set stairs, deck boards, railing) labor+material $26,540. Demo existing deck labor $2,000. Dump fee $500. Permit processing fee $450.",
      extractedJson: {
        client_name: 'Joey Wykoff',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4247',
        date: '08/26/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Demo',
            rate: 2000.0,
            quantity: 1,
            total: 2000.0,
            details: 'Labor Only: tear out existing deck.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Deck',
            rate: 26540.0,
            quantity: 1,
            total: 26540.0,
            details:
              "Includes all Labor, Includes all Material: premium pressure treated 17'x27', dig footers 18\" dia x 33\" depth, pour cement, install posts, ledger board, floor joists, bump out 36\" near stairs, 1 set of stairs, deck boards, railing system.",
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Processing Fee',
            rate: 450.0,
            quantity: 1,
            total: 450.0,
            details:
              'Labor Only: drawing fee, paperwork, drop off/pick up permit, gas/time, meeting inspectors.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Fees',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details: 'Added when known from city/county',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Dump Fee',
            rate: 500.0,
            quantity: 1,
            total: 500.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 29490.0,
        discount: 0,
        total: 29490.0,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          "Tear out old deck and build new premium pressure treated 17'x27' deck with footers, posts, ledger, joists, bump out, stairs, railing.",
      },
    },
    {
      jobType: 'Stamped Concrete Patio and Composite Deck Steps',
      clientName: 'Chantelle Cunningham',
      total: 12733.74,
      originalFilename: 'estimate_4257_chantelle_cunningham.pdf',
      pricingNotes:
        "Stamped concrete patio 24'x12' (288 sq ft) Ashlar Slate, labor+material $7,450.62 (~$25.87/sq ft). Grade yard $450. Dump fee $350. Composite deck steps 1 set 5-6' wide (Trex Naturals Coastal Bluff, pressure treated frame, hidden fasteners, no railing) labor+material $4,283.12. Gas surcharge $200.",
      extractedJson: {
        client_name: 'Chantelle Cunningham',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4257',
        date: '08/28/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Concrete Patio',
            rate: 7450.62,
            quantity: 1,
            total: 7450.62,
            details:
              "Includes all Labor, Includes all Material: 24'x12' (288 sq ft), fine grade/subgrade, compacted stone base, forms, 4000 PSI reinforced, Ashlar Slate stamp, integral color TBD, release agent, sealer, control joints, grading for drainage, cleanup.",
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: ['~$25.87/sq ft'],
            price_source: 'exact_match',
          },
          {
            description: 'Grade Yard',
            rate: 450.0,
            quantity: 1,
            total: 450.0,
            details: 'Grade yard for new concrete patio.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Dump Fee',
            rate: 350.0,
            quantity: 1,
            total: 350.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Deck Steps (Composite)',
            rate: 4283.12,
            quantity: 1,
            total: 4283.12,
            details:
              "Includes all Labor, Includes all Material: frame and build 1 set of steps 5-6' wide, pressure treated framing, Trex Naturals Coastal Bluff composite with hidden fasteners, no railing.",
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Gas Surcharge',
            rate: 200.0,
            quantity: 1,
            total: 200.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 12733.74,
        discount: 0,
        total: 12733.74,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          "Stamped concrete patio 24'x12' Ashlar Slate with grading and composite deck steps (Trex Naturals Coastal Bluff, 5-6' wide).",
      },
    },
    {
      jobType: 'Composite Deck Frame Rebuild Labor Only',
      clientName: 'Remon Sidarous',
      total: 13169.12,
      originalFilename: 'estimate_4258_remon_sidarous.pdf',
      pricingNotes:
        "Deck frame rebuild 12'x14' labor only $10,794.12 (client supplies all material): demo, 1 new footing, framing, ledger+flashing, install client-supplied composite decking+picture frame, 36-wide stairs, fascia, railing, siding repair. Demo existing deck framing $1,200 (separate). Dump $350, permit processing $450, drawing fee $225, gas $150.",
      extractedJson: {
        client_name: 'Remon Sidarous',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4258',
        date: '09/01/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Deck Renovation',
            rate: 10794.12,
            quantity: 1,
            total: 10794.12,
            details:
              "Labor Only, client provides all material: 12'x14' composite deck rebuild — demo existing framing, 1 new footing, new framing (posts/joists/blocking), ledger with flashing, install client-supplied composite decking + picture frame, 36\"-wide stairs + miter stair edges, install client-supplied fascia, install client-supplied railing, repair siding damaged by previous contractor.",
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: true,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Dump Fee',
            rate: 350.0,
            quantity: 1,
            total: 350.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Processing Fee',
            rate: 450.0,
            quantity: 1,
            total: 450.0,
            details: '',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Drawing Fee',
            rate: 225.0,
            quantity: 1,
            total: 225.0,
            details: '',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Gas Surcharge',
            rate: 150.0,
            quantity: 1,
            total: 150.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Demo Existing Deck Framing',
            rate: 1200.0,
            quantity: 1,
            total: 1200.0,
            details:
              'Labor Only (additional footer demo fees may apply).',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 13169.12,
        discount: 0,
        total: 13169.12,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          "Deck frame rebuild 12'x14' labor only (client supplies all material). Includes demo, new footing, framing, ledger with flashing, install client-supplied composite decking, stairs, fascia, railing, siding repair.",
      },
    },
    {
      jobType: 'Basement Remodel with Bathroom',
      clientName: 'Sylvia Nelson',
      total: 29323.61,
      originalFilename: 'estimate_4259_sylvia_nelson.pdf',
      pricingNotes:
        "Basement remodel labor+material $28,823.61: demo wall, 5-ft folding door, framing, paint walls/doors/trim, baseboard (new walls), drywall repair, 5' railing (labor only). Bathroom remodel within basement: relocate doors, new shower framing, plumbing tie-in + relocate (demo/fill concrete), standard vanity/top/sink/faucet/toilet, standard shower pan + surround, shower valve, LVP floor, paint bathroom, towel bar/TP holder. Dump fee $500.",
      extractedJson: {
        client_name: 'Sylvia Nelson',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4259',
        date: '09/03/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Basement Remodel',
            rate: 28823.61,
            quantity: 1,
            total: 28823.61,
            details:
              "Includes Labor, Includes Material (except 5' railing): demo wall to enlarge storage, 5-ft folding door + framing, paint basement walls/doors/trim, new baseboard on new walls, caulk, drywall repair, 5' railing at bottom of steps (labor only, material TBD), bathroom remodel (relocate doors, frame new shower/wall, tie into existing plumbing, demo concrete for plumbing relocation + new concrete fill, vanity/top/sink/faucet/toilet, standard shower pan + surround, shower valve + trim, LVP flooring in bathroom, paint bathroom, towel bar + TP holder), flooring pricing separate.",
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: [
              "5' railing material TBD",
              'Flooring pricing separate',
            ],
            price_source: 'exact_match',
          },
          {
            description: 'Dump Fee',
            rate: 500.0,
            quantity: 1,
            total: 500.0,
            details: '',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 29323.61,
        discount: 0,
        total: 29323.61,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          'Basement remodel including bathroom: wall demo, folding door, framing, painting, drywall repair, railing. Bathroom: plumbing relocation, shower framing, vanity, toilet, shower pan/surround, LVP floor, paint.',
      },
    },
    {
      jobType: 'Lean-To Roof Structure',
      clientName: 'Joe Gorley',
      total: 27191.14,
      originalFilename: 'estimate_4266_joe_gorley.pdf',
      pricingNotes:
        "Lean-to roof structure over existing deck labor+material $26,691.14: demo/reinstall 6-8 ft composite for footing access, footings+posts (~14 ft from house), LVL beams, 16-ft wide metal roof, roof-to-house flashing, PVC trim, soffit/fascia, siding adjustments, 6-inch gutters+downspouts, beadboard ceiling, electrical for 1 ceiling fan, Screeneze privacy wall 1 side, pressure wash. Permit processing $500.",
      extractedJson: {
        client_name: 'Joe Gorley',
        client_address: '',
        client_city_state_zip: '',
        client_phone: '',
        invoice_number: '4266',
        date: '09/16/2026',
        payment_terms: '',
        line_items: [
          {
            description: 'Lean To Roof Structure',
            rate: 26691.14,
            quantity: 1,
            total: 26691.14,
            details:
              'Includes all Labor, Includes all Material (client provides ceiling fan): remove 6-8 ft composite decking for access, excavate/install concrete footings, 2 structural posts ~14 ft from house, LVL beams + structural framing, 16 ft wide roof with metal roofing, flashing (roof-to-house), PVC trim on posts/beams, soffit + fascia, siding adjustments, 6" gutters + downspouts, beadboard ceiling (painted/stained per owner), electrical wiring for 1 ceiling fan, Screeneze privacy wall (one side), reinstall removed decking, pressure wash deck on completion.',
            includes_labor: true,
            includes_material: true,
            labor_only: false,
            customer_pays_material: false,
            notes: ['Client provides ceiling fan', 'Permit fees TBD'],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Fees',
            rate: 0.0,
            quantity: 1,
            total: 0.0,
            details: 'Added when known',
            includes_labor: false,
            includes_material: false,
            labor_only: false,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
          {
            description: 'Permit Processing Fee',
            rate: 500.0,
            quantity: 1,
            total: 500.0,
            details:
              'Labor Only: drawing sketch, applying, gas, time with inspectors.',
            includes_labor: true,
            includes_material: false,
            labor_only: true,
            customer_pays_material: false,
            notes: [],
            price_source: 'exact_match',
          },
        ],
        subtotal: 27191.14,
        discount: 0,
        total: 27191.14,
        material_breakdown: [],
        material_total: 0,
        payment_schedule: [],
        payments: [],
        summary:
          'Lean-to roof structure over existing composite deck: footings, posts, LVL beams, 16-ft metal roof, flashing, PVC trim, soffit/fascia, gutters, beadboard ceiling, electrical for ceiling fan, Screeneze privacy wall.',
      },
    },
  ];

  for (const estimate of estimates) {
    await prisma.referenceEstimate.create({
      data: {
        jobType: estimate.jobType,
        clientName: estimate.clientName,
        total: estimate.total,
        originalFilename: estimate.originalFilename,
        pricingNotes: estimate.pricingNotes,
        extractedJson: estimate.extractedJson as any,
      },
    });
    console.log(`Created reference estimate: ${estimate.jobType} - ${estimate.clientName}`);
  }

  console.log(`Seeded ${estimates.length} reference estimates.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
